### ISSUE TITLE
Black.stage.orientation

### ISSUE THREAD

**Issue by brunoandradebr** [MassiveHeights/Black#38]
`Black.stage.orientation = StageOrientation.LANDSCAPE`

It's not working on ios running on safari and when running added to home screen. Keeping rotating and do not lock orientation. 

*From example page* : [Orientation example](http://blacksmith2d.io/Docs/Examples/Stage/Orientations)

**Comment by 62316e** [comment]
Hello,

`Black.stage.orientation` is meant to lock stage orientation. By setting its value to `StageOrientation.LANDSCAPE` you are preventing stage from rotating. There is no easy way to lock orientation in safari. As an option you can show lock screen.

**Comment by brunoandradebr** [comment]
humm I thought It would lock orientation. 

> As an option you can show lock screen.

I didn't get it =/

**Comment by 62316e** [comment]
> humm I thought It would lock orientation.
It is not allowed to lock orientation from inside HTML. Orientation locking only possible on native apps.

![letterbox](https://user-images.githubusercontent.com/564381/41931485-eaf94aa0-7986-11e8-8c12-82856bca6fd4.png)

See image attached - it shows how `StageScaleMode.LETTERBOX` and `StageOrientation.LANDSCAPE` works. 

To achieve orientation lock there are few options:
1. manually rotate game container using CSS3 transform matrix 
2. show "ROTATE YOUR DEVICE" message to users when `Black.stage.isPortrait` is true.

I've added new example so you can play around with it. Try running example in fullscreen and rotate your device. http://blacksmith2d.io/Docs/Examples/Stage/Orientations%20Lock


Let me know if this helps.

**Comment by brunoandradebr** [comment]
Yeah got it! 

Your example is not working in ios 6s device, message still showing on landscape, but left bottom. Running on desktop browser with device emulator, works. And "Switch" is misspelled.

I'm writing my own engine too and I liked black interface, sounds like Actionscript 3. Very beutiful job ;)

Thanks for your patience.

**Comment by 62316e** [comment]
Example works fine on my side. Must be something server side related issue.
Thanks for your feedback. We appreciate it.

**Comment by brunoandradebr** [comment]
Yep, I cleaned safari cache and worked.
