### ISSUE TITLE
ScaleMode issue with StageOrientation.PORTRAIT

### ISSUE THREAD

**Issue by m31271n** [MassiveHeights/Black#57]
Recently, I'm using black-engine on a portrait layout page, and I think I found a issue.

The example code is [here](https://github.com/dodrio/black-engine-issue-scale-mode).

## example 1

```
Black.stage.scaleMode = StageScaleMode.LETTERBOX
Black.stage.setSize(750, 1500)
Black.stage.orientation = StageOrientation.PORTRAIT
```

When I am using `setSize(750, 1500)` and `StageOrientation.PORTRAIT`, black-engine returns following to me:

<img width="347" alt="1" src="https://user-images.githubusercontent.com/12194646/48057739-bc74ba80-e1ef-11e8-97db-38f1ec0da1a8.png">

But, I should be:

<img width="345" alt="2" src="https://user-images.githubusercontent.com/12194646/48057747-c26a9b80-e1ef-11e8-954e-18cee46fd807.png">

What is the problem? 750x1500 is a size that should fit PORTRAIT layout obviously, but It didn't work as expected.

## example 2

As I mentioned in example 1, black-engine seems doing something wrong. I have to use `setSize(1500, 750)` (swap width and height) in order to make it work.

```
Black.stage.scaleMode = StageScaleMode.LETTERBOX
Black.stage.setSize(1500, 750)
Black.stage.orientation = StageOrientation.PORTRAIT
```

It returns the right result:

<img width="345" alt="2" src="https://user-images.githubusercontent.com/12194646/48057757-c8607c80-e1ef-11e8-876c-0bfb79a79db6.png">

But it shouldn't return the right result. Because 1500x750 is a size that fits LANDSCAPE layout. It didn't work as expected.

---

Is it an issue?

**Comment by 62316e** [comment]
I dont think its a issue. 
But i agree that we need an extra tutorial about multi resolution and stage size modes.

Let me know if you have any suggestions

**Comment by m31271n** [comment]
When I want to have a stage which is `750x1500` and is portrait. I have to write:

```
Black.stage.setSize(1500, 750)
Black.stage.orientation = StageOrientation.PORTRAIT
```

I think this is violating the mortal intuition.

***
A better way for portrait layout, maybe:
```
Black.stage.setSize(750, 1500)
Black.stage.orientation = StageOrientation.PORTRAIT
```

A better way for landscape layout, maybe:
```
Black.stage.setSize(1500, 750)
Black.stage.orientation = StageOrientation.LANDSCAPE
```

What do you make of it?
