### ISSUE TITLE
Bitmap fonts don't display in Firefox

### ISSUE THREAD

**Issue by ThaisRobba** [MassiveHeights/Black#62]
**Describe the bug**
No bitmap text is displayed in Firefox.

**To Reproduce**
1. Go to [Bitmap font sample](https://blacksmith2d.io/Docs/Examples/Text/Bitmap-Font?fullscreen=true)
2. No text is displayed, console indicates error

**Expected behavior**
Same result as Chrome, with three lines of text.

**Screenshots**
![Captura de Tela (239)](https://user-images.githubusercontent.com/597287/54847315-cab60580-4cbc-11e9-9acb-0e44cc098b32.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 65.0.2

**Comment by 62316e** [comment]
Fixed
https://github.com/MassiveHeights/Black/commit/e0ff118dcc158408aedcf3601e550938dcc1361d
