### ISSUE TITLE
Engine and demo file size

### ISSUE THREAD

**Issue by hardylr** [MassiveHeights/Black#64]
In the README.md of the Black engine it is stated that the Donuts demo game is only 33KB gzipped for both engine and game. When building the demo game (https://github.com/MassiveHeights/Black-Donuts) using the latest Black engine (0.5.10) and running the production build script (npm run build) and analyzing the produced code bundle the gzipped bundle size is 56.25KB

**To Reproduce**
1. clone repo: https://github.com/MassiveHeights/Black-Donuts

2. run: `npm install`

3. install webpack-bundle-analyzer as a dev dependency to be able to analyse the code bundle. 
`npm install --save-dev webpack-bundle-analyzer`

4. Add the bundle analyzer as a plugin:

in webpack.config.js:
  `const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;`
 
add the analyser as a plugin:

`module.exports = {
  plugins: [
    new BundleAnalyzerPlugin()
  ]
}
`

5. create a production build
`npm run build`

The bundle analyzer will create an interactive treemap visualization of the contents of the bundle.
The Gzipped size of the bundle is 56.25KB. 

**Expected behavior**
The Gzipped size of the bundle should be 33KB as described inthe engin's readme.

**Screenshots**
![image](https://user-images.githubusercontent.com/7385384/69529413-ecb50580-0f78-11ea-8048-df3e4a363adf.png)

Bundle file size is very important for my project. I would like to achieve the smallest bundle size possible. The demo game bundle size is almost double the size claimed in the engine's readme file. 
Im not sure if the bundle size is related to a problem with my process or is there other optimizations that has to be done to achieve a small bundle size.

**Comment by 62316e** [comment]
Hello,

Thanks for reporting the issue. 
At some point i've got many requests about WebPack and zero about GCC so we decided to focus more on WebPack bundler. The bundle size is bigger but it is much easier to use.

I've just added an GCC example, gzipped size is about 34kb (readme is also updated).
https://github.com/MassiveHeights/Black-Donuts/tree/gcc

Let me know if you need even smaller build size.

**Comment by hardylr** [comment]
Hi,

Thank you very much for your speedy reply. Your GCC example does deliver a gzipped bundle size of about 34kb, which is absolutely amazing considering all the functionality included in the demo!

Webpack is definitely easier to configure, but GCC delivers a much smaller bundle size which is the main reason why I am using the Black engine. 

The build runs flawlessly on Chrome, FF and Edge, but I am having issues on IE11. 

From the gulp build file configuration of the GCC it seems like the bundle output is set to ECMASCRIPT5_STRICT which should be 100% compatible with IE11. 

I have tried to debug the error on IE11 and it seems to be an issue with the input class. Unfortunately I could not find a fix. Just launch your demo build using IE11 to duplicate the issue.

![image](https://user-images.githubusercontent.com/7385384/69611300-27c93e80-1036-11ea-81de-ca7ed0569018.png)

Thank again for you support. This little engine is proving to be very impressive! 
-An even smaller bundle size will always be welcome :)

**Comment by 62316e** [comment]
I was able to fix the issue with input but there are more. Will try to fix those.
