### ISSUE TITLE
PointerEvent issue in FF and Safari

### ISSUE THREAD

**Issue by hardylr** [MassiveHeights/Black#66]
The latest changes done in v0.5.11 to fix the incorrect pointerUp message done in Input.js is causing TypeError issues in FireFox and Safari. 

To replicate the issue run the Donuts-Black game (using black v0.5.11) in FireFox or Safari to see the below error message in the console.

![black](https://user-images.githubusercontent.com/7385384/71615078-0a007380-2bb8-11ea-9f37-ea971d8f9218.png)

It seems like the path property of Event objects is non-standard.

See this StackOverlow for more details:
https://stackoverflow.com/questions/39245488/event-path-undefined-with-firefox-and-vue-js

**Comment by 62316e** [comment]
Fixed in https://github.com/MassiveHeights/Black/pull/67
