### ISSUE TITLE
Vue-cli webpack issues due to empty black-engine.min.js

### ISSUE THREAD

**Issue by robjermy** [MassiveHeights/Black#69]
**Describe the bug**
The file "dist/black-engine.min.js" is empty. As such when dependencies are gathered this empty file is found for the engine resulting in failures at runtime.

**To Reproduce**
1. Go to "dist" folder
2. Click on 'black-engine.min.js'
3. See that the only line in it is 'use strict';

**Expected behavior**
It should contain the minified source code for the engine

**Comment by 62316e** [comment]
Thanks for reporting the issue. Fixed.
