### ISSUE TITLE
`FontFaceAssetLoader` doesn't work with spaces in Google webfont name

### ISSUE THREAD

**Issue by digitalbreed** [MassiveHeights/Black#70]
**Describe the bug**
`AssetManager` never emits the `complete` event if a queued Google webfont asset has spaces in its font name. This happens because the assignment of the `fontFamily` with the queued font name in `FontFaceAssetLoader` has no effect:
https://github.com/MassiveHeights/Black/blob/master/src/assets/loaders/FontFaceAssetLoader.js#L75
```
this.mTestingElement.style.fontFamily = name + ',' + this.mTestingFontName;
```
If `name` is e.g. `Press Start 2P` the `fontFamily` for the testing element remains `Courier New` as configured earlier, because in a list of comma-separated families, names with spaces should be quoted. Thus the width of the testing element never changes and a successful load of the font is not triggered.
The problem can be fixed by adding quotes around the generated fontFamily name:
```
this.mTestingElement.style.fontFamily = '"' + name + '",' + this.mTestingFontName;
```
Note that quotes need to be used for `TextField` fonts in that case, too:
```
let textField = new TextField('Test 123', '"Press Start 2P"', 0xffffff, 64, FontStyle.NORMAL, FontWeight.BOLD, 8, 0);
```
`FontFaceAssetLoader` should probably not loop indefinitely if the testing element width won't change. I suggest to include a failure counter, too, and emit an error after X attempts.

**To Reproduce**
1. Include `"black-engine": "0.5.12",` as a dependency
2. Instantiate a default `AssetManager`: `var assets = new AssetManager();`
3. Queue loading of Google Webfont with spaces: `assets.enqueueGoogleFont('Press Start 2P');`
4. Bind `complete` handler to a method `onAssetsLoaded` and start loading:
```
assets.on('complete', this.onAssetsLoaded, this);
assets.loadQueue();
```
5. Observe that `onAssetsLoaded` is never called.

**Expected behavior**
`onAssetsLoaded` should be called.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Chrome
 - Version: Version 85.0.4183.38 (Official Build) beta (64-bit)

**Comment by 62316e** [comment]
Thanks for reporting the issue. Fixed.

**Comment by 62316e** [comment]
Okay, here is another commit. The funny story is that "Font With Space A1" works just fine and "Font With Space 1A" is not. Was not related to spaces in font name.
cc @digitalbreed
