### ISSUE TITLE
Setting width or height on GameObject has no effect

### ISSUE THREAD

**Issue by digitalbreed** [MassiveHeights/Black#72]
**Describe the bug**
Setting `width` or `height` on a `GameObject` has no effect. The code updates the scale but doesn't store the passed in values. Example:
```
  // GameObject.js
  set width(value) {
    Debug.assert(!isNaN(value), 'Value cannot be NaN');

    this.scaleX = 1;
    const currentWidth = this.width;

    if (currentWidth != 0.0)
      this.scaleX = value / currentWidth;
  }
```
For more context, here's my use case: I tried creating a UI widget which consists of a frame (using a 9-slice-sprite) and lines of text. When creating the widget, I tried to specify width/height from the outside:
```
const widget = new TextWindow(); // extends GameObject
widget.x = 10;
widget.y = 10;
widget.width = this.stage.bounds.width / 2;
widget.height = 200;
this.add(widget);
```
which should allow me to create the child objects accordingly:
```
// TextWindow.onAdded:
// frame should take the entire size of the parent:
const frame = new Sprite('ui-frame');
frame.slice9grid = new Rectangle(10, 10, 4, 4);
frame.x = 0;
frame.y = 0;
frame.width = this.width;
frame.height = this.height;
this.add(frame);
```
However, `this.width` and `this.height` remain 0 even though the values were provided after creation.
If this is not how it is supposed to be done, what's the correct approach then?

**To Reproduce**
With Black 0.5.12, create a new `GameObject` and set the width to something >0. Then query the width and observe that it's still returned as 0.

**Expected behavior**
Changing the width programmatically should be accepted.

**Desktop (please complete the following information):**

* OS: macOS Mojave 10.14.6
* Browser: Chrome
* Version: Version 85.0.4183.38 (Official Build) beta (64-bit)

**Comment by digitalbreed** [comment]
While browsing through docs and source code I noticed this comment on `GameObject.onGetLocalBounds`:
```
Override this method if you need to specify GameObject size. Should be always be a local coordinates.
```
I created an extension of `GameObject` which seems to work, but frankly, I have no idea if I broke anything else:

```
import { GameObject, Debug, Rectangle } from 'black-engine';

export default class GameObjectEx extends GameObject {
	onGetLocalBounds(outRect = undefined) {
		outRect = outRect || new Rectangle();
		return outRect.set(0, 0, this.mWidth, this.mHeight);
	}

	set width(value) {
		Debug.assert(!isNaN(value), 'Value cannot be NaN');
		this.mWidth = value;
		this.setTransformDirty();
	}

	get width() {
		return super.width;
	}

	set height(value) {
		Debug.assert(!isNaN(value), 'Value cannot be NaN');
		this.mHeight = value;
		this.setTransformDirty();
	}

	get height() {
		return super.height;
	}
}
```

**Comment by 62316e** [comment]
Hi @digitalbreed,
Thanks for reporting the issue. 

Ive just tested this example and it works fine for me: https://blacksmith2d.io/Docs/Examples/Sprites/Slice-9-Grid

Both width/height methods returns non zero results for me. 

Would you be so kind as to send the test project to me?
Width/height does not store the values. If you you look inside the getter property source code you can see that size of the object is always relative to its parent and calculated inside onGetBounds. 

Eg if your widget is rotated it will affect the size of the object. This is intended behavior, but it should not be zero in your case.

**Comment by digitalbreed** [comment]
I believe your linked example works fine because `Sprite` overrides `onGetLocalBounds` and uses the texture size by default. But if you just want to have an empty `GameObject` with a given width/height as a wrapper for other components, like the UI window from my example, it doesn't work because here `onGetLocalBounds` returns a rect with width/height 0.

Here's a fiddle to demonstrate my problem: https://jsfiddle.net/nf8gtupa/4/

When you run it, you'll see that the `GameObject` reports to be 0x0 large. That means that no child objects can be created based on the size of this GO.

**Comment by 62316e** [comment]
Okay, now i understand your concern and this is indented behavior. Empty GameObject returns zero because it has no bounds and/or children objects. Please see `getBounds` instead.

`GameObject#onGetLocalBounds` also works as expected, both width and height uses `getBounds` method. 

Please check the fiddle: https://jsfiddle.net/62316e/0d4om3tu/8/
As you can see Widget no longer returns zero bounds.

For your case i would override `width`/`height` methods in Widget class. Please let me know if you need more help.
