### ISSUE TITLE
Typescript and Electron support

### ISSUE THREAD

**Issue by xstos** [MassiveHeights/Black#74]
I wanted to experiment with blacksmith using typescript inside electron and still have access to the source code so I can debug/learn it instead of treating it like a black box. Took me a few hours to get it full working, so I figured I'd post here as an FYI in case people care. I know it's sloppy to just copy the code into my own codebase, so if there are better ways i'm all ears :)

https://github.com/xstos/KatanaKinesis/tree/main/app

Here's the lazy port to typescript:
https://github.com/xstos/KatanaKinesis/tree/main/app/src/Black

I made a second project that supports hot reloading as well.
https://github.com/xstos/KatanaKinesis/tree/main/black

**Comment by 62316e** [comment]
Hi, thanks for sharing your research. 
Originally the engine was written in TypeScript but for simplicity we decided to go for JS. 

Since all the code has type comments im pretty sure those can be used to generate declarations for TS.
