### ISSUE TITLE
Stage is null when gameObject constructor is called

### ISSUE THREAD

**Issue by dmail** [MassiveHeights/Black#75]
**Describe the bug**
Whenever I try to access `this.stage` directly in the constructor it is null and I end up with errors like `Cannot read property 'on' of null`

**To Reproduce**
See https://codepen.io/dmail/pen/QWKRaVQ

**Expected behavior**
`this.stage` is accessible

**Screenshots**
![image](https://user-images.githubusercontent.com/443639/105571044-1fa98380-5d4d-11eb-8f8c-9c9290fcc59a.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - 
**Additional context**
I figured this out because I do not need to load asset in my minimalist game. So my code is not waiting for anything before trying to read `this.stage` and I have to force the loading of a fake asset or use `setTimeout` to fix that.

**Comment by 62316e** [comment]
Hi,

The reason because this.stage is null is because the Game object is not on the stage yet. 

Moving your code to ‘onAdded’ will fix the problem.

This is intended behavior. Please let me know if you ned further assistance.

**Comment by dmail** [comment]
Oh I see, it makes sense. Thank you. Right now I have a red rectangle moving on a canvas ahah.
